# Generated by Django 2.1 on 2019-01-12 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Header')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When was created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Image')),
                ('friend', models.ManyToManyField(blank=True, null=True, related_name='friend', to=settings.AUTH_USER_MODEL, verbose_name='Friend')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
